version: "3.8"

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/mydatabase"
    volumes:
      - .:/app:cached  # Usa `cached` para evitar sobrecarga no sistema de arquivos
      - /app/node_modules  # Garante que `node_modules` do container não seja sobrescrito

  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
